### ISSUE TITLE
Optimum term in quadratic expansion 

### ISSUE THREAD

**Issue by mforets** [JuliaReach/IntervalMatrices.jl#109]
Doing `(α + βx) x`  looses the dependency between the arguments, so it may be less precise using interval arithmetic. If there is a general rule, one has to find it by taking the derivative of the expression as in the paper, which is a particular case with alpha, beta being something like t and 1/2t^2.

```julia
julia> fprod(α, β, x) = (α + β*x)*x
fprod (generic function with 1 method)

julia> fsum(α, β, x) = α*x + β*x^2
fsum (generic function with 1 method)

julia> y = Interval(-1, 1)
[-1, 1]

julia> fprod(0.0, 1.0, y)
[-1, 1]

julia> fsum(0.0, 1.0, y) # fsum is tighter
[0, 1]

julia> y = Interval(-3, -2)
[-3, -2]

julia> fprod(1.0, 2.0, y) # fprod is tighter
[6, 15]

julia> fsum(1.0, 2.0, y)
[5, 16]
```

_Originally posted by @mforets in https://github.com/JuliaReach/IntervalMatrices.jl/pull/91#issuecomment-579806859_

**Comment by lucaferranti** [comment]
well the formula above doesn't work if $\beta=0$, but that's a trivial case to consider

**Comment by lucaferranti** [comment]
where should this go? I can open a PR for this.

Also does my assumption (alpha and beta are not intervals) hold? If it doesn't, it may make dependency problem worse

**Comment by mforets** [comment]
> where should this go?

i no longer remember the context in which this method was needed. (seems to be the scalar version of [this one](https://github.com/JuliaReach/IntervalMatrices.jl/blob/master/src/exponential.jl#L78)).

then i suggest to define the method on `exponentia.jl` and with signature

```julia
quadratic_expansion(A::Interval, α::Real, β::Real)
```
(NB this library doesn't depend on LazySets so there is no risk of confusion between LazySets.Interval and IntervalArithmetic.Interval)

> Also does my assumption (alpha and beta are not intervals) hold?

yes, that assumption holds

>  I can open a PR for this.

go for it :+1:

**Comment by lucaferranti** [comment]
Next that function should replace [this line](https://github.com/JuliaReach/IntervalMatrices.jl/blob/master/src/exponential.jl#L103) ? With a quick glance, the rest of the code should not suffer from dependency issues?
