### ISSUE TITLE
Docs not deployed

### ISSUE THREAD

**Issue by mforets** [JuliaReach/IntervalMatrices.jl#110]
https://juliareach.github.io/IntervalMatrices.jl/dev/#References-1 should contain 4 references (see [here](https://github.com/JuliaReach/IntervalMatrices.jl/blob/master/docs/src/index.md#references)) but contains only two.

**Comment by schillic** [comment]
I do not understand why the Travis script suddenly stopped working. My current explanation is that they changed their semantics.
