### ISSUE TITLE
Matrix exponential enclosures 

### ISSUE THREAD

**Issue by mforets** [JuliaReach/IntervalMatrices.jl#158]
https://epubs.siam.org/doi/abs/10.1137/19M1263431

**Comment by lucaferranti** [comment]
I had a quick read at this paper. If I understand correctly, that's concerned with finding a rigorous enclosure of the exponential of a _floating point_ matrix, not of a general interval matrix?

That being said, the INTLAB methods mentioned in the paper (`verifylss` and `verifyeig`) are both already implemented in ILA.jl,

**Comment by mforets** [comment]
(moved to the references wiki)
