### ISSUE TITLE
two-input constructor

### ISSUE THREAD

**Issue by lucaferranti** [JuliaReach/IntervalMatrices.jl#171]
Currently `IntervalMatrix(A, B)` constructs an interval matrix with center `A` and radius `B`. Whereas `Interval(a, b)` in IA.jl constructs an interval with lower bound `a` and upper bound `b`. I wonder whether this different behavior could be confusing for the user.

An alternative could be to overload `±` for interval matrices to construct an interval matrix from midpoint-radius and have IntervalMatrix(A, B) behave like the corresponding in IntervalArithmetic

**Comment by mforets** [comment]
Good point. I think the reason `IntervalMatrix(A, B)` behaves that way may be the analogy with `Hyperrectangle` in LazySets, where `Hyperrectangle(c, r)` constructs one by giving the center and radius, while `Hyperrectangle(low=l, high=h)` by extremal vectors.

I agree that it is reasonable to make it such that `Interval(A, B)` behaves in the same way as in the scalar case, `Interval(a, b)`.
