### ISSUE TITLE
Restructure matrix.jl

### ISSUE THREAD

**Issue by lucaferranti** [JuliaReach/IntervalMatrices.jl#174]
The matrix.jl file is pretty lengthy at the moment, I would propose to break it in a more modular way, e.g.

- `matrix.jl` -- type and constructors
- operations
  - arithmetic.jl -- like now
  - set.jl (set operations)
  - realvalued.jl (radius, diam, inf, sup)
 
what do you think?

**Comment by schillic** [comment]
I do not have an opinion but am fine with the proposal.

**Comment by mforets** [comment]
ok :+1: 

> set.jl (set operations)

setops.jl   (such name is used in other projects too..)

> realvalued.jl (radius, diam, inf, sup)

do you think that functionality specific for complex-value matrix should be added at some point?

**Comment by schillic** [comment]
> > realvalued.jl (radius, diam, inf, sup)
> 
> do you think that functionality specific for complex-value matrix should be added at some point?

I guess this was meant in contrast to "interval valued."

**Comment by lucaferranti** [comment]
Yes I meant "function returning a single element of the field over which intervals are defined". 🤓
