### ISSUE TITLE
rename `split` function

### ISSUE THREAD

**Issue by lucaferranti** [JuliaReach/IntervalMatrices.jl#179]
The current function `split` computes the midpoint and radius matrix of the interval matrix. Maybe the current name is a little misleading? By the name, I would think it does something like `bisect` or `mince`.

IntervalArithmetic.jl has a function called `midpoint_radius` which does exactly what split currently does, maybe we can extend that function?

**Comment by mforets** [comment]
makes sense to rename to `midpoint_radius` if that's used instead of `split` in IA :+1:
