### ISSUE TITLE
Add Zenodo badge to README

### ISSUE THREAD

**Issue by schillic** [JuliaReach/IntervalMatrices.jl#199]
I do not know how to obtain the version-independent badge. @mforets?

**Comment by lucaferranti** [comment]
10.5281/zenodo.2555934

it's on the right side at the bottom of the "versions" box

**Comment by schillic** [comment]
Yes, but there is a way to add a badge that auto-updates.

**Comment by schillic** [comment]
For the record, one adds the following to README.md:

```
[![zenodo][doi-img]][doi-url]

[doi-img]: https://zenodo.org/badge/XXX.svg
[doi-url]: https://zenodo.org/badge/latestdoi/XXX
```

where XXX is GitHub's repository ID, which can be found with [this algorithm](https://stackoverflow.com/a/47223479).
