### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by schillic** [JuliaReach/IntervalMatrices.jl#44]

**Comment by mforets** [comment]
@JuliaRegistrator register

**Comment by schillic** [comment]
@JuliaRegistrator register

**Comment by mforets** [comment]
@JuliaRegistrator register

**Comment by mforets** [comment]
@JuliaRegistrator register

**Comment by mforets** [comment]
@JuliaRegistrator register

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register

**Comment by mforets** [comment]
@JuliaRegistrator register

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register

**Comment by mforets** [comment]
@JuliaRegistrator register

**Comment by mforets** [comment]
@JuliaRegistrator register

**Comment by mforets** [comment]
@JuliaRegistrator register

**Comment by mforets** [comment]
@JuliaRegistrator register

**Comment by mforets** [comment]
@JuliaRegistrator register

**Comment by mforets** [comment]
@JuliaRegistrator register

**Comment by mforets** [comment]
@JuliaRegistrator register
