### ISSUE TITLE
Rump fast interval matrix multiplication

### ISSUE THREAD

**Issue by dpsanders** [JuliaReach/IntervalMatrices.jl#46]
It would be great to implement Rump’s method for efficiently multiplying interval matrices using only floating-point matrix operations (with rounding mode changes).

**Comment by dpsanders** [comment]
Many things like this can be found in his review article: https://www.cambridge.org/core/journals/acta-numerica/article/verification-methods-rigorous-results-using-floatingpoint-arithmetic/770FE58E5293985CCAB770AF09C4F3FF

**Comment by dpsanders** [comment]
See algorithm 9.1 on page 43 of that article.

**Comment by dpsanders** [comment]
Unfortunately that uses rounding mode changes, which can be accomplished with the `SetRounding.jl` package. We should check that that actually works with Julia's LAPACK wrappers.

**Comment by mforets** [comment]
Also related: https://www.sciencedirect.com/science/article/pii/S0377042711005449
