### ISSUE TITLE
Implement test for positive definiteness

### ISSUE THREAD

**Issue by dpsanders** [JuliaReach/IntervalMatrices.jl#47]
Rump has a test for positive definiteness of interval matrices.

**Comment by dpsanders** [comment]
Apparently the algorithm I was remembering is not about interval matrices at all, but rather about floating-point matrices:

http://www.ti3.tuhh.de/paper/rump/Ru06c.pdf

**Comment by schillic** [comment]
If I understand correctly, there is no algorithm to implement here.
