### ISSUE TITLE
Constructor for identity matrix

### ISSUE THREAD

**Issue by schillic** [JuliaReach/IntervalMatrices.jl#49]
It is handy to have a function for creating an identity matrix. 

Maybe `Diagonal(one_interval, n)` "just works" (not tested).

**Comment by mforets** [comment]
one can do `Diagonal([-1..11, -1..1])` or repeat this vector as in:

```julia
julia> Diagonal(repeat([-1..1],  2)) |> IntervalMatrix
2×2 IntervalMatrix{Float64,Interval{Float64},Diagonal{Interval{Float64},Array{Interval{Float64},1}}}:
 [-1, 1]   [0, 0]
  [0, 0]  [-1, 1]
```

**Comment by mforets** [comment]
> Maybe Diagonal(one_interval, n) "just works" (not tested).

It doesn't work.

The idiomatic way of creating an identity is to use `I`, or `Matrix(one(T)I, n, n)` for some numeric type `T`, see eg. [here](https://stackoverflow.com/questions/57270276/identity-matrix-in-julia). One can apply it like so

```julia
julia> IntervalMatrix(Matrix(Interval(1)I, 2, 2))
2×2 IntervalMatrix{Float64,Interval{Float64},Array{Interval{Float64},2}}:
 [1, 1]  [0, 0]
 [0, 0]  [1, 1]
```

Here is a proposal: add a new constructor `IntervalMatrix(::UniformScaling{Interval{T}}, n, [m]=n))`. The identity matrix of order `n` can then be constructed with the command `IntervalMatrix(Interval(1)I, n)`.

**Comment by schillic** [comment]
I agree, but does a non-square identity matrix make sense?

**Comment by mforets** [comment]
If n and m are different, the matrix is not the identity, but the constructor can be used. I followed the convention in Base. Actually the default number for the number of columns being the number of rows does *not* work in Base as shown below (but i defined it [here](The identity matrix of order n can then be constructed with the command IntervalMatrix(Interval(1)I, n). I don't have a strong opinion on keeping the default value or making m and n mandatory).

```julia
julia> using LinearAlgebra

julia> Matrix(1.0I, 2, 3)
2×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0

julia> Matrix(1.0I, 3, 2)
3×2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0
 0.0  0.0

julia> Matrix(1.0I, 3)
ERROR: MethodError: no method matching Array{T,2} where T(::UniformScaling{Float64}, ::Int64)
Closest candidates are:
  Array{T,2} where T(::UniformScaling, ::Integer, ::Integer) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/uniformscaling.jl:391
  Array{T,2} where T(::UndefInitializer, ::Integer, ::Integer) at baseext.jl:22
  Array{T,2} where T(::UniformScaling, ::Tuple{Int64,Int64}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/uniformscaling.jl:392
Stacktrace:
 [1] top-level scope at REPL[4]:1

julia> Matrix(1.0I, 3, 3)
3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0
```

**Comment by schillic** [comment]
I totally agree that `identity(Interval{T}, n)` or something similar should work because the identity is square.
