### ISSUE TITLE
Add reference

### ISSUE THREAD

**Issue by mforets** [JuliaReach/IntervalMatrices.jl#67]
https://mediatum.ub.tum.de/doc/1287218/1287218.pdf

**Comment by schillic** [comment]
What do you mean? [`exponential.jl`](https://github.com/JuliaReach/IntervalMatrices.jl/blob/master/src/exponential.jl) and [`correction_hull.jl`](https://github.com/JuliaReach/IntervalMatrices.jl/blob/master/src/correction_hull.jl) have that reference in every docstring.

**Comment by mforets** [comment]
Sorry, i meant to add that reference in [this part](https://juliareach.github.io/IntervalMatrices.jl/latest/#References-1). The discussion about interval matrices, and proofs are extended wrt ref. [1].

We should also add this reference: https://ieeexplore.ieee.org/document/1446499
