### ISSUE TITLE
Add "Theory" section in the docs

### ISSUE THREAD

**Issue by mforets** [JuliaReach/IntervalMatrices.jl#87]
- introduce notation for interval matrices `[A]`

- revise example from the Quickstart about squaring interval matrices (ref. https://github.com/JuliaReach/IntervalMatrices.jl/pull/80, Kosheleva et al's paper).

- non-associativity of matrix products

- SUE

**Comment by lucaferranti** [comment]
I was planning to add such an article under the "Explanations" section in ILA.jl, where I would define what an interval matrix is, what properties it has (and hasn't) and some basic taxonomy (regular, strongly regular, H, M  etc.).

**Comment by mforets** [comment]
:+1:  this package should focus on documenting its API. more comprehensive explanations belong to ILA docs.
